### ISSUE TITLE
Panic - thread 'main' panicked at 'Ratio should be between 0 and 1 inclusively.'

### ISSUE THREAD

**Issue by parandeploy** [alphastrata/nvtop#1]
Built from source.
Unable to run the program.
`thread 'main' panicked at 'Ratio should be between 0 and 1 inclusively.'
..../.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.23.0/src/widgets/gauge.rs:62:9                                                                                                                                 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

I should probably also note that I'm running this with hybrid graphics enabled, and connected to a power supply.

**Comment by alphastrata** [comment]
> Built from source. Unable to run the program. `thread 'main' panicked at 'Ratio should be between 0 and 1 inclusively.' ..../.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.23.0/src/widgets/gauge.rs:62:9 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
> 
> I should probably also note that I'm running this with hybrid graphics enabled, and connected to a power supply.

@ltrook21 what GPU do you have? do you know the architecture?

**Comment by alphastrata** [comment]
@ltrook21 maybe fix : https://github.com/alphastrata/nvtop/tree/fix/panic-issue%231 much appreciated if you can try.

**Comment by parandeploy** [comment]
Sure, I'll give it try between tomorrow and Monday. Unfortunately I don't have a lot of time. Also it seems that the link you posted is giving me a 404.

Thanks for the work so far, and being so quick with a response!

**Comment by alphastrata** [comment]
I'm pretty sure some work done this after noon will either of fixed this, or if you pass in the `--log <somepath to save your log>.log` as an arg it'll tell me exactly what/where something failed.

Lemme know

**Comment by parandeploy** [comment]
So I ran it again after pulling the changes, still getting this error:
`                      [2023-10-08][19:53:53][TRACE][nvtop::app][23] crossterm initialisation successful
              thread 'main' panicked at 'Ratio should be between 0 and 1 inclusively.', /home/rook/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.23.0/src/widgets/gauge.rs:62:9
            note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

FWIW, I have an Nvidia RTX 3070 TI in a gaming laptop, 2022 release so pretty new hardware.

**Comment by alphastrata** [comment]
> So I ran it again after pulling the changes, still getting this error: ` [2023-10-08][19:53:53][TRACE][nvtop::app][23] crossterm initialisation successful thread 'main' panicked at 'Ratio should be between 0 and 1 inclusively.', /home/rook/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.23.0/src/widgets/gauge.rs:62:9 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`
> 
> FWIW, I have an Nvidia RTX 3070 TI in a gaming laptop, 2022 release so pretty new hardware.

somewhere the graphs' using the `.ratio` are getting values they're unable to clamp... weird.
is this off the latest main?

**Comment by parandeploy** [comment]
Yep

**Comment by alphastrata** [comment]
Are you able to use `nvidia-smi` their native tool?

**Comment by bktech2021** [comment]
#12 this can solve the problem

comment-blocked re-scan beceause discover_gpus not implemented, 

also added 
```rust
let percentage = match avg.is_nan() {
        true => 0.0,
        false => avg
    };
    let label = match avg.is_nan() {
        true => "No fan".to_string(),
        false => format!("{:.1}%", avg)
    };
```

so if there is no fans, it will show no fans. (i think there can be a more efficient way)


![image](https://github.com/alphastrata/nvtop/assets/80114298/e39d9a07-0bb0-48df-a666-116ee88d93f0)

**Comment by parandeploy** [comment]
So I don't know if this might be helpful at all but nvtop works perfectly on my desktop with an Nvidia RTX 2060. The problem is on my laptop with an RTX 3070 ti... 
I will give you an update re. my laptop tomorrow! Thanks!

**Comment by bktech2021** [comment]
> So I don't know if this might be helpful at all but nvtop works perfectly on my desktop with an Nvidia RTX 2060. The problem is on my laptop with an RTX 3070 ti... I will give you an update re. my laptop tomorrow! Thanks!

Because on desktop, your GPU has a fan and it's connected on your GPU card. On the laptop, your mobile GPU doesn't have fans, yes it has fans, but they are connected to your motherboard, like any case fans in your desktop. So, the program doesn't detect it as a GPU fan. 

on the program, the fan percentage becomes NaN, and you are clamping it, and becomes NaN, and ratatui says it must be between 0 and 1. and the pull request i made it makes it "If fan spin is NaN, its zero and label is 'No fans'".

i tested it on a GTX1060 6GB and Victus 16 laptop, works fine.

**Comment by alphastrata** [comment]
@bktech2021's work (I think) will fix this @ltrook21  -- I just suggested a few changes and we can get it merged in.

**Comment by parandeploy** [comment]
Awesome. Will give it a shot between tonight and tomorrow so we can close this out.

**Comment by parandeploy** [comment]
Sorry, took me a while to try this again.
It's working perfectly fine now! Thanks again for the great work!
![image](https://github.com/alphastrata/nvtop/assets/22264309/8a4580ea-0768-408c-8e46-a9d514605f29)
