### ISSUE TITLE
nvtop name is used by another oldest project

### ISSUE THREAD

**Issue by luzfcb** [alphastrata/nvtop#17]
I don't know if the name `nvtop` was chosen on purpose however, it has the same name as another older tool, which can result in people reporting issues with the original `nvtop` on this repository instead of the old project and vice versa. 

Maybe `rnvtop`? 

Anyway, defining names has always been a separate science in the world of technology.

https://github.com/Syllo/nvtop
https://github.com/run-ai/rntop
https://github.com/rapidloop/rtop
https://github.com/RedCarrottt/nvmon

**Comment by alphastrata** [comment]
Hey,

Thanks for the post -- Yes, I _unfortunately_ became aware of this after taking it live etc, the main issue I'm grappling with is that one cannot yank things from crates.io (the place `cargo` publishes it). 

I will, at the least be renaming the repo tho soon.
